# permissions for end users to view routemonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routemonitor-viewer-role
rules:
- apiGroups:
  - monitoring.openshift.io
  resources:
  - routemonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.openshift.io
  resources:
  - routemonitors/status
  verbs:
  - get
